### ISSUE TITLE
Scope to something below `HTTPure`

### ISSUE THREAD

**Issue by cprussin** [cprussin/purescript-httpure-rest-router#1]
@akheron what do you think about following a pattern like what `XMonad` does and scoping packages like this one under `HTTPure.Contrib` instead of `HTTPure` directly?  That way, anything under `HTTPure` is the `HTTPure` library itself, where anything under `HTTPure.Contrib` is extensions built on top of it.  At least in `XMonad`, this helps a lot with disambiguating where components live

**Comment by akheron** [comment]
Good idea, fixed!
